#ifndef MAINCONTROLLER_H
#define MAINCONTROLLER_H

#include <QApplication>
#include <QFontDatabase>
#include <QMainWindow>
#include "../ui_mainmenu.h"
#include "../ui_endmenu.h"
#include "gamecontroller.h"

/*!
 * \class MainController
 *
 * Run and manage the applicaction, controls her flow.
 *
 */
class MainController : public QObject {
    Q_OBJECT

public:
    /*!
     * \brief Initialization and first showing.
     */
    MainController( QApplication *a );

public slots:
    void exit_game();

    // Integrated view functionality
    void show_game();
    void show_menu();
    void show_end_menu( int winner );

private slots:
    /*!
     * Block associated spinbox elements
     */
    void onWhitePlayerVirtualityChanged( int value );
    /*!
     * Block associated spinbox elements
     */
    void onBlackPlayerVirtualityChanged( int value );

private:

    QMainWindow mainWindow; //!< Main window (Of the whole program).

    /**
     * User interfaces generated by QT forms system.
     */
    Ui::MainMenu mainMenu;
    Ui::EndMenu endMenu;

    GameController *gc; //!< Pointer to the game system, acceding by his controller.

    QApplication *app;  //!< Pointer to the main application to manage.
};

#endif // MAINCONTROLLER_H
